# Generated by Django 3.2.6 on 2021-12-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicbeats', '0005_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('channel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000000)),
                ('music', models.CharField(max_length=100000000)),
            ],
        ),
    ]
